audioPath = 'D:\Audioproject1\source\';
audioDir = dir([audioPath '*.mp3']);
[Y, Fs] = audioread([audioPath audioDir(5).name]);
%y = Y(:,1);
ty = (0:length(Y)-1)/Fs;
wind = hamming(1024);
overlap = 400;
nfft = 2^nextpow2(length(wind));
[s,F,T] = stft(Y,Fs,'Window',wind,'OverlapLength',overlap,'FFTLength',nfft);
smag = abs(s);
sphs = angle(s);
[x,tx,info] = stftmag2sig(smag,nfft,Fs,'Window',wind,'OverlapLength',overlap);
shift = 10;
Rate = 2;
R = WSOLA(x, Fs, Rate, shift);
figure;
subplot(2,1,1);
plot(Y);
title('original');
axis([1 length(Y) -0.5 0.5]);
subplot(2,1,2);
plot(R);
title('wsola');
axis([1 length(Y) -0.5 0.5]);
sound(R,Fs);
%audiowrite('slowaudio5.wav',R,Fs);